# Generated by Django 4.0.1 on 2022-03-11 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0003_task_executed_reset_password_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reset_password_code',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reset_password_code',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
