# Generated by Django 4.0.1 on 2022-03-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_reset_password_code_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reset_password_code',
        ),
    ]
